require('core.plugin_config.lsp')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.nvim-cmp')
require('core.plugin_config.nvim-tree')
-- require('lua.core.plugin_config.nvim-web-devicons')
